query {
  repository(owner:"_REPO_OWNER_", name:"_REPO_NAME_") {
    pullRequests(first:100) {
      totalCount
      edges {
        cursor
        node {
          number
          state
          title
          createdAt
          author{
            login
          }
          mergedAt
          reviews(first: 100){
            nodes {
              createdAt
            }
          }
          timelineItems(first: 100, itemTypes: [LABELED_EVENT, ASSIGNED_EVENT, MERGED_EVENT, READY_FOR_REVIEW_EVENT, CLOSED_EVENT]) {
            edges {
              node {
                __typename
                ... on ClosedEvent {
                  actor {
                    login
                  }
                  createdAt
                }
                ... on LabeledEvent {
                  label {
                    name
                  }
                  actor {
                    login
                  }
                  createdAt
                }
                ... on MergedEvent {
                  actor {
                    login
                  }
                  createdAt
                }
                ... on ReadyForReviewEvent {
                  actor {
                    login
                  }
                  createdAt
                }
                ... on AssignedEvent {
                  actor {
                    login
                  }
                  createdAt
                }
              }
            }
          }
        }
      }
    }
  }
}
